version: '3'
services:
  app:
    build: 
      context: .
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/app
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    volumes:
      - ./.data/redis:/var/lib/redis
    restart: always